### PR TITLE
Remove weird artifact

### LINKED ISSUE #23: fix issue with weird extra column at the end?

### PR DESCRIPTION
**Pull request by sandersky**
# PATCH

resolves #23 

**Before:**
screen shot 2016-05-03 at 8 35 06 pm

**After:**
screen shot 2016-05-03 at 8 35 20 pm

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Is the black border part of the table?  If so I believe the intention of the gutter was to place the scrollbar outside (to the right) of the border - also can you confirm cross-browser on this (sorry, have to ask)

**Comment by sandersky** [comment]
The black border is just in the screenshots for some reason while it doesn't actually exist on the page. I'll perform the browser testing and make any updates required (if any are required).

**Comment by sandersky** [comment]
Verified it works in Chrome on OS X and IE 11 on Windows 7. Firefox isn't rendering the scrollbar on the proper container but that issue already exists prior to my change. Going to go ahead and add a new issue for that and get this PR green to merge.

**Comment by rox163** [comment]
great timing on this fix 😃

**Comment by rox163** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-list/pull-request/24/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-list)

**Comment by sglanzer-fire** [comment]
Thanks @sandersky!

**Pull request merged**
