### PR TITLE
Enable multi-select behavior

### PR DESCRIPTION
**Pull request by frosetti**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* Added disableDeselectAll. If true, clicking outside of the checkbox in a list item will no longer deselect all of the other items.

### CODE REVIEW

**Review by notmessenger — DISMISSED** [review]
@frosetti Can you please provide a screen recording or a series of image captures elaborating on what your changelog description is describing?  If I visit http://ciena-frost.github.io/ember-frost-list/#/ I can already select multiple items, can shift-click to do so, ctrl click, etc.  I do not understand what the change in behavior is.

Can you also add a demonstration of this to the demo app so that others can see the behavior illustrated as well?

**Comment by TheOtherDude** [comment]
To give context, we need this feature because we have a very large list and accidentally missing the select box is a huge pain for our users. This feature has been requested by Katie Parmeson and other people on the UX team.

**Comment by notmessenger** [comment]
I'm not trying to capriciously block this but I still do not understand the difference in the behavior introduced in this PR and would still like to see what new behavior these changes provide.

**Comment by TheOtherDude** [comment]
The changelog might be more clear as something like...

* Added disableDeselectAll. If true, clicking outside of the checkbox in a list item will no longer deselect all of the other items.

**Comment by notmessenger** [comment]
Only interacting with checkboxes:
* can select individual boxes and they remain checked
  * can select individual boxes again and they become unchecked
* can ctrl-click individual boxes and they remain checked
  * can ctrl-click individual boxes again and they become unchecked
* can select a box and then shift-click another to select the range
  * can then deselect individual checkboxes

Only interacting with the rows (not the checkboxes):
* Can make a checkbox be checked by selecting a row
* Selecting another row deselects the previous checkbox and checks the new one
* If selecting a row and shift-click another the entire range becomes checked
  * clicking another row then deselects all but the one just clicked on
* ctrl-clicking various rows allows each successive row to be checked 

What we should be doing is first synchronizing the behavior between what happens when interacting with the checkbox vs the rows - are they supposed to behave differently?   Once that is squared away it may be that this PR isn't even needed.

**Comment by cstolli** [comment]
@notmessenger, Forrest convinced me there are valid use cases for both types of behavior, so an option makes sense.

**Comment by cstolli** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-list/pull-request/175/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-list)

**Pull request merged**
