### PR TITLE
Add factory-guy mocking layer and remove mirage

### PR DESCRIPTION
**Pull request by juwara0**
# PATCH
# CHANGELOG
- **Added** factory-guy mocking layer with factories
- **Updated** tests to use factory-guy instead of mirage
- **Removed** mirage mocking layer

---

This change is [Reviewable](https://reviewable.io/reviews/ciena-frost/ember-frost-list/59)

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-list/pull-request/59/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-list)

**Comment by TheOtherDude** [comment]
http://ciena-frost.github.io/ember-frost-list is broked :(

**Comment by juwara0** [comment]
@TheOtherDude - Thanks for reporting. I am aware that this is broken and am trying to get it back up.

**Comment by juwara0** [comment]
@TheOtherDude I went ahead and opened an issue to track the broken demo app at: http://ciena-frost.github.io/ember-frost-list/. The issue is: https://github.com/ciena-frost/ember-frost-list/issues/60

**Pull request merged**
