### PR TITLE
Up everything

### PR DESCRIPTION
**Pull request by EWhite613**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [x] #major# - incompatible API change

# CHANGELOG
* Use latest major for `ember-frost-core`

### CODE REVIEW

**Comment by juwara0** [comment]
The blueprint will need to be updated as well.

**Review by notmessenger — CHANGES_REQUESTED** [review]
* The blueprint needs to be updated as well.
* Change the title of this PR to provide contextually-relevant information.

**Comment by juwara0** [comment]
This will need to be a server major since you are moving the version of core up a major.

**Comment by EWhite613** [comment]
Depends on https://github.com/ciena-frost/ember-frost-sort/pull/69 , reopen when merged

**Review by notmessenger — APPROVED** [review]

**Comment by notmessenger** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-list/pull-request/156/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-list)

**Pull request merged**
